import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import wasm from 'vite-plugin-wasm';

export default defineConfig({
  plugins: [
    react(),
    // Enables importing .wasm files generated by wasm-pack --target bundler
    wasm(),
  ],
  build: {
    // vite-plugin-wasm emits a top-level `await` in the WASM initialisation
    // chunk.  The default Vite target (Chrome 87 / ES2020) pre-dates top-level
    // await support (Chrome 89 / Safari 15 / Firefox 89).  Raise the target so
    // esbuild doesn't reject the generated code.
    target: ['chrome89', 'edge89', 'firefox89', 'safari15'],
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: './src/test/setup.ts',
  },
});
